package com.samhg.authentication.key;

import java.util.concurrent.TimeUnit;

public final class KeyConstants {

    private KeyConstants() {
        // prevent instantiation.
    }

    /**
     * Default value for the number of generated bytes before reseeding a {@link ReseedingSecureRandom}.
     */
    public static final int DEFAULT_RESEED_BYTES = 100_000;

    /**
     * Default value for the amount of time between reseeding a {@link ReseedingSecureRandom}.
     */
    public static final long DEFAULT_RESEED_INTERVAL = TimeUnit.MINUTES.toMillis(1);

    /**
     * Algorithm name and provider used by for PRNG.
     */
    public static final String ALGORITHM = "SHA1PRNG", PROVIDER = "SUN";

}